//! generates the Astrolabe_* export thunks, see proxy.rs

/// exports taken from the 7.0 client
const EXPORTS: &[&str] = &[
    "Astrolabe_AddDetectionThread",
    "Astrolabe_BuriedReport",
    "Astrolabe_CrashReport",
    "Astrolabe_CrashReportSetCustomData",
    "Astrolabe_DisableBuried",
    "Astrolabe_EnableAreaSensitive",
    "Astrolabe_EnableHttpProxy",
    "Astrolabe_GameLogReport",
    "Astrolabe_GetCurrentTime",
    "Astrolabe_GetLocalTime",
    "Astrolabe_GetOccurTime",
    "Astrolabe_Init",
    "Astrolabe_InstallCrashReport",
    "Astrolabe_InstallGameLog",
    "Astrolabe_InstallHang",
    "Astrolabe_InstallLogPlugin",
    "Astrolabe_InstallMemMonitor",
    "Astrolabe_InstallReplay",
    "Astrolabe_IsLastLaunchCrashed",
    "Astrolabe_LogPluginClose",
    "Astrolabe_LogPluginDisableCallback",
    "Astrolabe_LogPluginFlush",
    "Astrolabe_LogPluginSetUploadConfig",
    "Astrolabe_LogPluginSetUploadSeperateConfig",
    "Astrolabe_LogPluginUpload",
    "Astrolabe_LogPluginUploadWithAttachment",
    "Astrolabe_LogPluginWrite",
    "Astrolabe_OnHang",
    "Astrolabe_RemoveDetectionThread",
    "Astrolabe_ReplayFightingReport",
    "Astrolabe_ReplayReport",
    "Astrolabe_SendHeartBeat",
    "Astrolabe_SetConfig",
    "Astrolabe_SetCustomData",
    "Astrolabe_SetFtcSwitch",
    "Astrolabe_SetJavaVM",
    "Astrolabe_SetLrsag",
    "Astrolabe_SetNetworkStateFunction",
    "Astrolabe_SetReportEnv",
    "Astrolabe_SetWindowThreadId",
    "Astrolabe_Start",
    "Astrolabe_StartAcc",
    "Astrolabe_StartReport",
    "Astrolabe_StartWithoutReport",
    "Astrolabe_StartWithoutReportAndTime",
    "Astrolabe_TimeDestroy",
    "Astrolabe_UploadFileByChunks",
];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let mut generated = String::new();
    generated.push_str("// Generated by build.rs - do not edit.\n\n");

    // same order as the jump table
    generated.push_str(&format!(
        "pub const NAMES: [&str; {}] = [\n{}];\n\n",
        EXPORTS.len(),
        EXPORTS
            .iter()
            .map(|n| format!("    \"{n}\",\n"))
            .collect::<String>()
    ));

    generated.push_str(&format!(
        "/// one slot per export, filled by proxy::init\npub static mut REAL: [usize; {}] = [0; {}];\n\n",
        EXPORTS.len(),
        EXPORTS.len()
    ));

    // asm, so the caller's registers and stack are untouched
    for (i, name) in EXPORTS.iter().enumerate() {
        generated.push_str(&format!(
            "core::arch::global_asm!(\n    \".globl {name}\",\n    \"{name}:\",\n    \
             \"jmp qword ptr [rip + {{tbl}} + {}]\",\n    tbl = sym REAL,\n);\n",
            i * 8
        ));
    }

    let out_dir_str = std::env::var("OUT_DIR").unwrap();
    let out_dir = std::path::Path::new(&out_dir_str);
    let out = out_dir.join("astrolabe_proxy.rs");
    std::fs::write(&out, generated).expect("failed to write the generated proxy");

    // name them as exports so the loader sees them
    if std::env::var("CARGO_CFG_TARGET_ENV").unwrap() == "msvc" {
        // link.exe: one /EXPORT switch per symbol
        for name in EXPORTS {
            println!("cargo:rustc-cdylib-link-arg=/EXPORT:{name}");
        }
    } else {
        // GNU ld (mingw): /EXPORT is not understood, feed it a .def file instead
        let mut def = String::from("LIBRARY ext\nEXPORTS\n");
        for name in EXPORTS {
            def.push_str(&format!("  {name}\n"));
        }
        let def_path = out_dir.join("astrolabe_exports.def");
        std::fs::write(&def_path, def).expect("failed to write the .def file");

        // absolute path: the linker's cwd is not necessarily the crate root
        let def_str = def_path.to_str().expect("non-utf8 OUT_DIR");
        println!("cargo:rustc-cdylib-link-arg={def_str}");
        println!("cargo:rerun-if-changed={def_str}");
    }
}
